<?php
	$webAffiche="今天网站正式开放";
	$webKeyName="中国建配网|中国建配网重庆站|中国建材配送网|重庆建配网|建配网|重庆建材配送|平价建材专业配送|平价姐姐|平价姐姐1397|建材配送|建筑装饰|建筑材料|装饰材料|建材|家装|装修预算|材料价格|材料预算|木地板|地板|橱柜|玻璃|五金锁具|涂料油漆|成品门窗|家用电器|木业板材|家具楼梯|墙纸|卫浴洁具|石材制品|墙砖地砖|灯具开关|吊顶材料|水电材料|PVC排水|PP-R管|PVC线管|强弱电线||开关插座|开关面板|灯具||砂岩|花岗石|大理石|文化石|防腐木|石膏板|绿舟|好易润德|五木|天京|美心门|蓝鸟名门|雅艺防盗门窗|塑钢门窗|无框阳台|现代漆|乳胶漆|真石漆|立邦|华润|多乐士|晾衣架|拉手|厨房拉篮|滑轨|锁具|玻璃砖系列|千姿镜系列|欧克橱柜|海尔橱柜|洁达橱柜|新象地板|升达木地板|老缅地板|";
	$webRootUrl="htttp://172.17.247.148/bluesea";
	$webRootPath="/website";
	$webDirPath="/bluesea";
	$jifenOpen="yes";
	$jifenValReg="100";
	$jifenValLogin="5";
	$jifenTimeLogin="60";
	$jifenTopLogin="15";
	$jifenValBuy="10";
	$jifenTopBuy="500";
	$jifenValArt="5";
	$jifenTopArt="10";
	$cupToArg="100";
	$argToGold="100";
	$jifenChargeOpen="yes";
	$jifenCharge="100";
	$moneyChargeOpen="yes";
	$moneyChargeLess="100";
	$moneyCharge="1";
	$orderTime="7";
?>